GitHub git:// is deprecated
Fixes this error when building the docker file

```
  ERROR: Command errored out with exit status 128:
   command: git clone --filter=blob:none -q git://github.com/quantopian/MongoDBProxy.git /usr/src/app/var/server-venv/src/mongodbproxy
       cwd: None
  Complete output (3 lines):
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.4]: errno=Connection timed out
```