Upgrade `python-daemon` to 2.2.4 for compatibility with recent Python
With recent versions of Python 3, opening a client shell fails with
this stack trace in the client logs:

```
Traceback (most recent call last):
  File "client/endpoints/shell.py", line 54, in <module>
    main()
  File "client/endpoints/shell.py", line 49, in main
    with manager():
  File "/opt/penguindome/client/var/client-venv/lib/python3.8/site-packages/daem
on/daemon.py", line 273, in __init__
    detach_process = is_detach_process_context_required()
  File "/opt/penguindome/client/var/client-venv/lib/python3.8/site-packages/daemon/daemon.py", line 821, in is_detach_process_context_required
    if is_process_started_by_init() or is_process_started_by_superserver():
  File "/opt/penguindome/client/var/client-venv/lib/python3.8/site-packages/daemon/daemon.py", line 798, in is_process_started_by_superserver
    if is_socket(stdin_fd):
  File "/opt/penguindome/client/var/client-venv/lib/python3.8/site-packages/daemon/daemon.py", line 764, in is_socket
    file_socket = socket.fromfd(fd, socket.AF_INET, socket.SOCK_RAW)
  File "/usr/lib/python3.8/socket.py", line 544, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket
```

Upgrading to the current version of `python-daemon` fixes this.